# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Manu Phatak
email: bionikspoon@gmail.com
description: >
    The man. The myth. The Legend.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bionikspoon.github.io" # the base hostname & protocol for your site
github_username:  bionikspoon

# Build settings
markdown: kramdown

# Github required
lsi: false
safe: true
source: ./
incremental: false
highlighter: rouge
gist:
    noscript: false
